# Generated by Django 2.2 on 2019-04-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='部门名称')),
                ('code', models.IntegerField(unique=True, verbose_name='部门编号')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='员工姓名')),
                ('email', models.EmailField(max_length=64, verbose_name='邮箱')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Department', to_field='code', verbose_name='部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rbac.User')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='业务名称')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(help_text='必须为数字', verbose_name='项目时间')),
                ('date', models.DateField(auto_now_add=True, verbose_name='工作日期')),
                ('work_des', models.TextField(blank=True, max_length=500, null=True, verbose_name='工作描述')),
                ('manager', models.ForeignKey(limit_choices_to={'depart': [1001, 1005]}, on_delete=django.db.models.deletion.CASCADE, related_name='user_man', to='crm.UserInfo', verbose_name='项目主管')),
                ('work_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Work', verbose_name='业务')),
            ],
        ),
        migrations.CreateModel(
            name='StaffRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[('checked', '已签到'), ('vacate', '请假'), ('late', '迟到'), ('absence', '缺勤'), ('leave_early', '早退')], default='checked', max_length=64, verbose_name='签到记录')),
                ('score', models.IntegerField(choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (70, 'B-'), (60, 'C+'), (50, 'C'), (40, 'C-'), (0, ' D'), (-1, 'N/A')], default=-1, verbose_name='评分')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='负责员工')),
                ('work_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.WorkRecord', verbose_name='项目第几天')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('phone', models.CharField(help_text='手机号必须唯一', max_length=64, unique=True, verbose_name='手机号')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('education', models.IntegerField(blank=True, choices=[(1, '重点大学'), (2, '普通本科'), (3, '独立院校'), (4, '民办本科'), (5, '大专'), (6, '民办专科'), (7, '高中'), (8, '其他')], null=True, verbose_name='学历')),
                ('firm', models.CharField(blank=True, max_length=64, null=True, verbose_name='所属公司')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='详细住址')),
                ('work_status', models.IntegerField(blank=True, choices=[(1, '在职'), (2, '无业')], default=1, null=True, verbose_name='职业状态')),
                ('status', models.IntegerField(choices=[(1, '已合作'), (2, '未合作')], default=2, help_text='选择客户此时的状态', verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='咨询日期')),
                ('current_date', models.DateField(null=True, verbose_name='当前销售顾问的接单日期')),
                ('last_consult_date', models.DateField(verbose_name='最后跟进日期')),
                ('consultant', models.ForeignKey(limit_choices_to={'depart_id': 1001}, on_delete=django.db.models.deletion.CASCADE, related_name='user_consultant', to='crm.UserInfo', verbose_name='销售顾问')),
                ('work', models.ManyToManyField(to='crm.Work', verbose_name='咨询业务')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDistribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('status', models.IntegerField(choices=[(1, '正在跟进'), (2, '已合作'), (3, '三天未跟进'), (4, '15天未成单')], default=1, verbose_name='跟进状态')),
                ('memo', models.CharField(max_length=255, verbose_name='说明')),
                ('consultant', models.ForeignKey(limit_choices_to={'depart_id': 1001}, on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='销售顾问')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='crm.CustomerObj', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('emergency_contract', models.CharField(blank=True, max_length=32, null=True, verbose_name='紧急联系人')),
                ('company', models.CharField(blank=True, max_length=128, null=True, verbose_name='公司')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在区域')),
                ('date', models.DateField(blank=True, help_text='格式yyy-mm-dd', null=True, verbose_name='合作开始时间')),
                ('memo', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerObj', verbose_name='客户信息')),
                ('work_list', models.ManyToManyField(blank=True, to='crm.Work', verbose_name='合作业务')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='跟进日期')),
                ('note', models.TextField(verbose_name='跟进内容...')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='跟踪人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerObj', verbose_name='所咨询客户')),
            ],
        ),
    ]
