# Generated by Django 2.2 on 2019-04-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='manager',
            field=models.ForeignKey(default='', limit_choices_to={'depart': [1005]}, on_delete=django.db.models.deletion.CASCADE, related_name='user_man', to='crm.UserInfo', verbose_name='项目主管'),
        ),
    ]
