# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-08 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190429_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='note',
            field=models.TextField(verbose_name='跟进内容'),
        ),
        migrations.AlterField(
            model_name='customerobj',
            name='status',
            field=models.IntegerField(choices=[(1, '已合作'), (2, '未合作')], default=2, help_text='选择客户此时的状态', verbose_name='合作状态'),
        ),
    ]
